/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.operaciones;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;
/**
 *
 * @author Personal
 */
public class Salida extends javax.swing.JFrame {

    /**
     * Creates new form Salida
     */
    public Salida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNumHab = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonRecibo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(880, 580));

        jLabel1.setText("Numero de habitacion:");

        jButton1.setText("Cuenta");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonRecibo.setText("Crear Recibo");
        jButtonRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReciboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRecibo)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldNumHab, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(jButton1))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNumHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRecibo)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReciboActionPerformed
        // TODO add your handling code here:
        try{
            PDDocument documento = new PDDocument();
            PDPage pagina = new PDPage(PDRectangle.A5);
            documento.addPage(pagina);
            
            PDPageContentStream contenido = new PDPageContentStream(documento, pagina);
            
            contenido.beginText();
            contenido.setFont(PDType1Font.TIMES_ITALIC, 18);
            contenido.newLineAtOffset(40,pagina.getMediaBox().getHeight()-125);
            contenido.showText("Sábanas limpias, agua caliente y tragos fuertes.");
            contenido.endText();
            
            contenido.beginText();
            contenido.setFont(PDType1Font.TIMES_ROMAN, 11);
            contenido.newLineAtOffset(65,pagina.getMediaBox().getHeight()-140);
            contenido.showText("Ubicación: Blvrd Riviera AJEI 254, Nuevo Vallarta, Nayarit.");
            contenido.endText();
            
            contenido.beginText();
            contenido.setFont(PDType1Font.COURIER_BOLD, 11);
            contenido.newLineAtOffset(15,pagina.getMediaBox().getHeight()-166);
            contenido.showText("Fecha: ");
            contenido.endText();
            
            contenido.beginText();
            contenido.setFont(PDType1Font.COURIER_BOLD, 11);
            contenido.newLineAtOffset(15,pagina.getMediaBox().getHeight()-182);
            contenido.showText("Nombre del huesped:");
            contenido.endText();
            
            contenido.beginText();
            contenido.setFont(PDType1Font.COURIER_BOLD, 11);
            contenido.newLineAtOffset(15,pagina.getMediaBox().getHeight()-199);
            contenido.showText("Ciudad de Origen: ");
            contenido.endText();
            
            contenido.beginText();
            contenido.setFont(PDType1Font.COURIER_BOLD, 11);
            contenido.newLineAtOffset(15,pagina.getMediaBox().getHeight()-216);
            contenido.showText("Fecha de Ingreso: ");
            contenido.endText();
            
            contenido.beginText();
            contenido.setFont(PDType1Font.COURIER_BOLD, 11);
            contenido.newLineAtOffset(15,pagina.getMediaBox().getHeight()-233);
            contenido.showText("Fecha de Salida: ");
            contenido.endText();
            
            contenido.beginText();
            contenido.setFont(PDType1Font.COURIER_BOLD, 11);
            contenido.newLineAtOffset(15,pagina.getMediaBox().getHeight()-250);
            contenido.showText("Tipo de habitacion: ");
            contenido.endText();
            
            contenido.beginText();
            contenido.setFont(PDType1Font.COURIER_BOLD, 11);
            contenido.newLineAtOffset(15,pagina.getMediaBox().getHeight()-267);
            contenido.showText("Costo de Habitacion: ");
            contenido.endText();
            
            contenido.beginText();
            contenido.setFont(PDType1Font.COURIER_BOLD, 11);
            contenido.newLineAtOffset(15,pagina.getMediaBox().getHeight()-284);
            contenido.showText("Dias Hospedado: ");
            contenido.endText();
            
            contenido.beginText();
            contenido.setFont(PDType1Font.COURIER_BOLD, 11);
            contenido.newLineAtOffset(15,pagina.getMediaBox().getHeight()-301);
            contenido.showText("Total a pagar sin cargos extra: ");
            contenido.endText();
            
            contenido.beginText();
            contenido.setFont(PDType1Font.COURIER_BOLD, 11);
            contenido.newLineAtOffset(15,pagina.getMediaBox().getHeight()-318);
            contenido.showText("Total a pagar con cargos extra: ");
            contenido.endText();
            
            contenido.beginText();
            contenido.setFont(PDType1Font.COURIER_BOLD, 11);
            contenido.newLineAtOffset(15,pagina.getMediaBox().getHeight()-335);
            contenido.showText("Lista de cargos extra: ");
            contenido.endText();
            
            PDImageXObject firma = PDImageXObject.createFromFile("firma1.png", documento);
            contenido.drawImage(firma, 150,pagina.getMediaBox().getHeight()-565);
            
            PDImageXObject logo = PDImageXObject.createFromFile("logo.png", documento);
            contenido.drawImage(logo, 90,pagina.getMediaBox().getHeight()-110);
                       
            contenido.beginText();
            contenido.setFont(PDType1Font.COURIER_BOLD_OBLIQUE, 11);
            contenido.newLineAtOffset(40,pagina.getMediaBox().getHeight()-585);
            contenido.showText("AJEI Resort agradece su preferencia vuelva pronto.");
            contenido.endText();
         
            contenido.close();
            documento.save("documento.pdf");
        }catch(Exception x){
            System.out.println("Error "+x.getMessage().toString());
            x.printStackTrace();
        }
    }//GEN-LAST:event_jButtonReciboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonRecibo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldNumHab;
    // End of variables declaration//GEN-END:variables
}
