/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ventanas_presentacion;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;

/**
 *
 * @author Usuario
 */
public class Index extends javax.swing.JFrame {

    private boolean musicaIniciada;

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.musicaIniciada = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jButtonEstadisticas = new javax.swing.JButton();
        jButtonCheckIn = new javax.swing.JButton();
        jButtonCheckOut = new javax.swing.JButton();
        jLabelBtn1 = new javax.swing.JLabel();
        jLabelBtn2 = new javax.swing.JLabel();
        jLabelBtn3 = new javax.swing.JLabel();
        jLabelConfiguracion = new javax.swing.JLabel();
        jLabelMusica = new javax.swing.JLabel();
        jLabelMenu = new javax.swing.JLabel();
        jPanelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 580));
        setResizable(false);

        jPanelMenu.setBackground(new java.awt.Color(255, 186, 106));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(220, 580));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEstadisticas.setBackground(new java.awt.Color(255, 186, 106));
        jButtonEstadisticas.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/index/bar-chart.png"))); // NOI18N
        jButtonEstadisticas.setText("Estadísticas");
        jButtonEstadisticas.setAutoscrolls(true);
        jButtonEstadisticas.setBorder(null);
        jButtonEstadisticas.setBorderPainted(false);
        jButtonEstadisticas.setContentAreaFilled(false);
        jButtonEstadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEstadisticas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonEstadisticas.setIconTextGap(10);
        jButtonEstadisticas.setInheritsPopupMenu(true);
        jButtonEstadisticas.setOpaque(true);
        jButtonEstadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEstadisticasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEstadisticasMouseExited(evt);
            }
        });
        jButtonEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstadisticasActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, 210, 50));

        jButtonCheckIn.setBackground(new java.awt.Color(255, 186, 106));
        jButtonCheckIn.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/index/edit.png"))); // NOI18N
        jButtonCheckIn.setText("Check In");
        jButtonCheckIn.setAutoscrolls(true);
        jButtonCheckIn.setBorder(null);
        jButtonCheckIn.setBorderPainted(false);
        jButtonCheckIn.setContentAreaFilled(false);
        jButtonCheckIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCheckIn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCheckIn.setIconTextGap(10);
        jButtonCheckIn.setInheritsPopupMenu(true);
        jButtonCheckIn.setOpaque(true);
        jButtonCheckIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCheckInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCheckInMouseExited(evt);
            }
        });
        jButtonCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckInActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 219, 210, 50));

        jButtonCheckOut.setBackground(new java.awt.Color(255, 186, 106));
        jButtonCheckOut.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonCheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/index/exit-symbol.png"))); // NOI18N
        jButtonCheckOut.setText("Check Out");
        jButtonCheckOut.setAutoscrolls(true);
        jButtonCheckOut.setBorder(null);
        jButtonCheckOut.setBorderPainted(false);
        jButtonCheckOut.setContentAreaFilled(false);
        jButtonCheckOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCheckOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCheckOut.setIconTextGap(10);
        jButtonCheckOut.setInheritsPopupMenu(true);
        jButtonCheckOut.setOpaque(true);
        jButtonCheckOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCheckOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCheckOutMouseExited(evt);
            }
        });
        jButtonCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckOutActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 279, 210, 50));

        jLabelBtn1.setBackground(new java.awt.Color(175, 87, 0));
        jLabelBtn1.setToolTipText("");
        jLabelBtn1.setOpaque(true);
        jPanelMenu.add(jLabelBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 159, 10, 50));

        jLabelBtn2.setBackground(new java.awt.Color(175, 87, 0));
        jLabelBtn2.setToolTipText("");
        jLabelBtn2.setOpaque(true);
        jPanelMenu.add(jLabelBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 219, 10, 50));

        jLabelBtn3.setBackground(new java.awt.Color(175, 87, 0));
        jLabelBtn3.setToolTipText("");
        jLabelBtn3.setOpaque(true);
        jPanelMenu.add(jLabelBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 279, 10, 50));

        jLabelConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/index/cogwheel.png"))); // NOI18N
        jLabelConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelConfiguracionMouseClicked(evt);
            }
        });
        jPanelMenu.add(jLabelConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, -1, -1));

        jLabelMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/index/musicOn.png"))); // NOI18N
        jLabelMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMusicaMouseClicked(evt);
            }
        });
        jPanelMenu.add(jLabelMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 472, -1, -1));

        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/index/bar-menu.png"))); // NOI18N
        jLabelMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseClicked(evt);
            }
        });
        jPanelMenu.add(jLabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        jPanelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContenedor.setPreferredSize(new java.awt.Dimension(870, 580));

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 878, Short.MAX_VALUE)
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1116, 619);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEstadisticasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEstadisticasMouseEntered
        Color color = new Color(Integer.parseInt("AF5700", 16));
        this.jButtonEstadisticas.setBackground(color);
    }//GEN-LAST:event_jButtonEstadisticasMouseEntered

    private void jButtonEstadisticasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEstadisticasMouseExited
        Color color = new Color(Integer.parseInt("FFBA6A", 16));
        this.jButtonEstadisticas.setBackground(color);
    }//GEN-LAST:event_jButtonEstadisticasMouseExited

    private void jButtonCheckInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCheckInMouseEntered
        Color color = new Color(Integer.parseInt("AF5700", 16));
        this.jButtonCheckIn.setBackground(color);
    }//GEN-LAST:event_jButtonCheckInMouseEntered

    private void jButtonCheckInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCheckInMouseExited
        Color color = new Color(Integer.parseInt("FFBA6A", 16));
        this.jButtonCheckIn.setBackground(color);
    }//GEN-LAST:event_jButtonCheckInMouseExited

    private void jButtonCheckOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCheckOutMouseEntered
        Color color = new Color(Integer.parseInt("AF5700", 16));
        this.jButtonCheckOut.setBackground(color);
    }//GEN-LAST:event_jButtonCheckOutMouseEntered

    private void jButtonCheckOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCheckOutMouseExited
        Color color = new Color(Integer.parseInt("FFBA6A", 16));
        this.jButtonCheckOut.setBackground(color);
    }//GEN-LAST:event_jButtonCheckOutMouseExited

    private void jLabelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseClicked
        if (this.jLabelMenu.getX() > 10) {
            this.jPanelContenedor.setSize(1040, this.jPanelContenedor.getHeight());
            this.jPanelContenedor.setLocation(60, this.jPanelContenedor.getY());
            if (this.jPanelContenedor.getComponentCount() > 0) {
                this.jPanelContenedor.getComponent(0).setSize(this.jPanelContenedor.getSize());
            }
            this.jPanelMenu.setSize(60, this.jPanelMenu.getHeight());
            Animacion.Animacion.mover_izquierda(50, 5, 0, 2, this.jLabelMenu);
        } else {
            this.jPanelContenedor.setSize(880, this.jPanelContenedor.getHeight());
            this.jPanelContenedor.setLocation(220, this.jPanelContenedor.getY());
            if (this.jPanelContenedor.getComponentCount() > 0) {
                this.jPanelContenedor.getComponent(0).setSize(this.jPanelContenedor.getSize());
            }
            this.jPanelMenu.setSize(220, this.jPanelMenu.getHeight());
            Animacion.Animacion.mover_derecha(5, 165, 0, 2, this.jLabelMenu);
        }
    }//GEN-LAST:event_jLabelMenuMouseClicked

    private void jLabelConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConfiguracionMouseClicked
        if (this.jLabelMusica.getX() == 10) {
            Animacion.Animacion.mover_izquierda(10, -50, 2, 2, this.jLabelMusica);
        } else {
            Animacion.Animacion.mover_derecha(-50, 10, 2, 2, this.jLabelMusica);
        }
    }//GEN-LAST:event_jLabelConfiguracionMouseClicked

    private void jLabelMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMusicaMouseClicked
        if (this.musicaIniciada) {
            this.musicaIniciada = false;
            this.jLabelMusica.setIcon(new ImageIcon(getClass().getResource("/img/index/musicOff.png")));
        } else {
            this.musicaIniciada = true;
            this.jLabelMusica.setIcon(new ImageIcon(getClass().getResource("/img/index/musicOn.png")));
        }
    }//GEN-LAST:event_jLabelMusicaMouseClicked

    private void jButtonEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstadisticasActionPerformed
        this.abrirJFrameEnPanelContenedor(new Estadisticas());
    }//GEN-LAST:event_jButtonEstadisticasActionPerformed

    private void jButtonCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckOutActionPerformed
        this.abrirJFrameEnPanelContenedor(new CheckOut());
    }//GEN-LAST:event_jButtonCheckOutActionPerformed

    private void jButtonCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckInActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonCheckInActionPerformed

    private void abrirJFrameEnPanelContenedor(Object jF) {
        // si existe algún componente en la
        // en el panel contenedor, lo removemos
        if (this.jPanelContenedor.getComponentCount() > 0) {
            this.jPanelContenedor.removeAll();
        }

        JInternalFrame jFHijo = (JInternalFrame) jF;

        ((javax.swing.plaf.basic.BasicInternalFrameUI) jFHijo.getUI()).setNorthPane(null);
        //jFHijo.setSize(this.jPanelContenedor.getSize());

        this.jPanelContenedor.add(jFHijo);
        jFHijo.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheckIn;
    private javax.swing.JButton jButtonCheckOut;
    private javax.swing.JButton jButtonEstadisticas;
    private javax.swing.JLabel jLabelBtn1;
    private javax.swing.JLabel jLabelBtn2;
    private javax.swing.JLabel jLabelBtn3;
    private javax.swing.JLabel jLabelConfiguracion;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelMusica;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
